### ISSUE TITLE
ElementGui.lua not found

### ISSUE THREAD

**Issue by lolpedro** [Helfima/helmod#98]
The error on the image down happens every time I load a save or try to create a new game
I had check the files and the __helmod__/core/ElementGui.lua is there on the mod .zip
![helmod error](https://user-images.githubusercontent.com/31799981/30240892-e1f727ba-9570-11e7-8218-d9a9d85b1165.png)

**Comment by Helfima** [comment]
Arf, the file had bad name, you can rename with start upper case ElementGui.lua actualy is elementGui.lua
I fix it in this week

**Comment by Helfima** [comment]
fixed in v0.6.4
It 's strange locally I have ElementGui.lua but not on github, it's renamed on github

**Comment by lolpedro** [comment]
the error persists after the update. I have the correct name in the file this time and I get the same error

**Comment by Helfima** [comment]
You have uploaded by fororio mod site?
verify you have not another version in folder mod
[helmod_0.6.4.zip](https://github.com/Helfima/helmod/files/1295841/helmod_0.6.4.zip)

**Comment by Tyrindor** [comment]
https://mods.factorio.com/mods/Helfima/helmod/discussion/19518

Getting this on 1.6.4, had to revert.

**Comment by lolpedro** [comment]
the same error still persists after downloading the version on factorio mod website.

**Comment by Helfima** [comment]
@lolpedro try version 0.6.5
if you have error on core.Format you must reinstall factorio
if the same it s crazy

**Comment by TheCasualObserver** [comment]
Also had this problem in 0.6.4, and 0.6.5 resolved the issue for me. Thanks for the quick fix.

**Comment by lolpedro** [comment]
0.6.5 solved it xb
Thanks for the fix xb

**Comment by Helfima** [comment]
@lolpedro :) i have only switch 2 lines
